site_name: Liska Linux Wiki
site_description: A Documentation Wiki For Liska Linux
repo_url: https://github.com/source-liskalinux/wiki

copyright: >
  &copy; Liska Linux Wiki | 2026 &bull;
  General Public License v3 or Later

theme:
  name: null
  custom_dir: liska-theme
  favicon: assets/logo.svg
  logo: assets/logo.svg

nav:
  - 'Main page': 'index.md'
  - 'Table of contents': 'table-of-contents'
  - Contributing: 'contributing'
  - 'Wiki news': 'wiki-news'

extra:
  social:
    - icon: fa-brands fa-github
      link: https://github.com/source-liskalinux
      name: Liska Linux Github Source Repository
    - icon: fa-brands fa-discord
      link: https://discord.gg/
      name: Liska Linux Discord Community Server
    - icon: fa-solid fa-globe
      link: https://liskalinuxproject.web.app
      name: Liska Linux Project Website

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      guess_lang: true      
  - pymdownx.superfences    
  - pymdownx.inlinehilite
