site_name: Liska Linux Wiki
site_description: A Documentation Wiki For Liska Linux
repo_url: https://github.com/source-liskalinux/wiki

copyright: >
  &copy; Liska Linux Wiki | 2026 &bull;
  General Public License v3 or Later

nav:
  - 'Main page': 'index.md'
  - 'Table of contents': 'table-of-contents'
  - Contributing: 'contributing'
  - 'Wiki news': 'wiki-news'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/source-liskalinux
      name: Liska Linux Github Source Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
      name: Liska Linux Discord Community Server
    - icon: fontawesome/solid/globe
      link: https://liskalinuxproject.web.app
      name: Liska Linux Website

theme:
  name: material
  favicon: assets/logo.svg
  logo: assets/logo.svg

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light Mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      guess_lang: true      
  - pymdownx.superfences    
  - pymdownx.inlinehilite
